apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.15.0
  count: 1
  elasticsearchRef:
    name: {{ include "efk.fullname" . }}
  # config:
  #    elasticsearch.requestHeadersWhitelist:
  #    - authorization
  podTemplate:
    spec:
      containers:
      - name: kibana
        {{- with .Values.kibana.env }}
        env:
          {{- toYaml . | nindent 12}}
        {{- end }}
        resources:
          requests:
            memory: {{ .Values.kibana.resources.requests.memory | default "1Gi" | quote }}
            cpu: {{ .Values.kibana.resources.requests.cpu | default "0.5" | quote }}
          limits:
            memory: {{ .Values.kibana.resources.limits.memory | default "2.5Gi"| quote }}
            cpu: {{ .Values.kibana.resources.limits.cpu | default "2"| quote }}
    {{- if .Values.kibana.dedicated -}}
      {{- with .Values.kibana.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 10}}
      {{- end }}
      {{- with .Values.kibana.tolerations }}
      tolerations:
        {{- toYaml . | nindent 10}}
      {{- end }}
    {{- end }}